language: python
sudo: required
dist: bionic
python: "3.7"
install:
  - pip3 install homeassistant
script:
  - hass -c . --script check_config --info all
before_install:
  - sudo apt-get install -y libavformat-dev libavcodec-dev libavdevice-dev libavutil-dev libswscale-dev libswresample-dev libavfilter-dev
  - mv travis_secrets.yaml secrets.yaml
