matrix:
  include:
    - python: 3.6
    - python: 3.7
      dist: xenial
      sudo: true
install:
  - pip3 install homeassistant
script:
  - hass -c . --script check_config --info all
before_install:
  - mv travis_secrets.yaml secrets.yaml
