  - path: security
    name: Security
    icon: 'mdi:security'
    cards:
      - type: 'custom:auto-entities'
        card:
          type: entities
          title: Timers
        filter:
          include:
            - domain: timer
      - type: 'custom:auto-entities'
        card:
          type: entities
          title: Motion zone
          show_header_toggle: false
        filter:
          include:
            - domain: binary_sensor
              name: "*Zone"
      - type: 'custom:auto-entities'
        card:
          type: entities
          title: Motion occupancy
          show_header_toggle: false
        filter:
          include:
            - domain: binary_sensor
              name: "*Occupancy*"
      - type: 'custom:auto-entities'
        card:
          type: entities
          title: Doors & Windows
          show_header_toggle: false
        filter:
          include:
            - domain: binary_sensor
              name: "*on_off*"
      - type: picture-entity
        entity: camera.drive
        show_name: false
        show_state: false
      - type: picture-entity
        entity: camera.fennacam
        show_name: false
        show_state: false
      