- platform: mqtt
  name: "MQTT Cover"
  command_topic: "home-assistant/cover/set"
  state_topic: "home-assistant/cover/state"
  availability_topic: "home-assistant/cover/availability"
  qos: 0
  retain: true
  payload_open: "OPEN"
  payload_close: "CLOSE"
  payload_stop: "STOP"
  state_open: "open"
  state_closed: "closed"
  payload_available: "online"
  payload_not_available: "offline"
  optimistic: false
  value_template: '{{ value.x }}'
  tilt_command_topic: 'home-assistant/cover/tilt'
  tilt_status_topic: 'home-assistant/cover/tilt-state'
  tilt_min: 0
  tilt_max: 180
  tilt_closed_value: 70
  tilt_opened_value: 180
