- platform: template
  sensors:
    braviatv:
      friendly_name: 'Sony Bravia TV'
      value_template: "{{ 'Online' if is_state('device_tracker.braviatv', 'home') else 'Offline' }}"
      icon_template: 'mdi:television'
    philipshue:
      friendly_name: 'Philips Hue Bridge'
      value_template: "{{ 'Online' if is_state('device_tracker.philipshue', 'home') else 'Offline' }}"
      icon_template: 'mdi:lightbulb'
