- platform: dsmr
  port: /dev/ttyUSB0
  dsmr_version: 4

- platform: template
  sensors:
    power_peak_costs_daily:
      friendly_name: "Power Costs Peak Daily"
      unit_of_measurement: '€'
      value_template: "{{ (states('sensor.daily_power_peak')|float * 0.23296) | round(2) }}"
    power_offpeak_costs_daily:
      friendly_name: "Power Costs Offpeak Daily"
      unit_of_measurement: '€'
      value_template: "{{ (states('sensor.daily_power_offpeak')|float * 0.23296) | round(2) }}"
    gas_costs_daily:
      friendly_name: "Gas Costs Daily"
      unit_of_measurement: '€'
      value_template: "{{ (states('sensor.daily_gas')|float * 0.73944) | round(2) }}"
    power_peak_costs_monthly:
      friendly_name: "Power Costs Peak Monthly"
      unit_of_measurement: '€'
      value_template: "{{ (states('sensor.monthly_power_peak')|float * 0.23296) | round(2) }}"
    power_offpeak_costs_monthly:
      friendly_name: "Power Costs Offpeak Monthly"
      unit_of_measurement: '€'
      value_template: "{{ (states('sensor.monthly_power_offpeak')|float * 0.23296) | round(2) }}"
    gas_costs_monthly:
      friendly_name: "Gas Costs Monthly"
      unit_of_measurement: '€'
      value_template: "{{ (states('sensor.monthly_gas')|float * 0.73944) | round(2) }}"

# Kitchen Fridge power sensors
- platform: mqtt
  state_topic: "tele/sonoffpow1/ENERGY"
  name: "Fridge Power Consumption"
  force_update: true
  icon: mdi:power-plug
  unit_of_measurement: "w"
  value_template: '{{ (value_json.Power|float) | round(2) }}'

- platform: mqtt
  state_topic: "tele/sonoffpow1/ENERGY"
  name: "Fridge Power Today"
  force_update: true
  icon: mdi:power-plug
  unit_of_measurement: "w"
  value_template: '{{ (value_json.Today | float) | round(2) }}'
