- platform: google_travel_time
  name: Home to work
  api_key: !secret google_api_key
  origin: zone.home
  destination: !secret google_travel_work
- platform: google_travel_time
  name: Work to home
  api_key: !secret google_api_key
  origin: !secret google_travel_work
  destination: zone.home
