
- platform: template
  sensors: 
    house_key_handover_new:
      friendly_name: 'New house handover'
      value_template: "{{ ((strptime('01032019', '%d%m%Y').timestamp() - as_timestamp(now())) / 86400)|round }}"
      icon_template: mdi:key-plus
      unit_of_measurement: days
      entity_id: sensor.date
    house_key_handover_old:
      friendly_name: 'Old house handover'
      value_template: '{{ ((strptime("18032019", "%d%m%Y").timestamp() - as_timestamp(now())) / 86400)|round }}'
      icon_template: mdi:key-minus
      unit_of_measurement: days
      entity_id: sensor.date
    house_moving_day:
      friendly_name: 'Moving day'
      value_template: '{{ ((strptime("16032019", "%d%m%Y").timestamp() - as_timestamp(now())) / 86400)|round }}'
      icon_template: mdi:package-variant
      unit_of_measurement: days
      entity_id: sensor.date