# Clean when clean on leave is enabled
- alias: 'Vacuum when everbody leaves'
  trigger:
    - platform: state
      entity_id: person.daniel, person.laura
      to: 'not_home'
  condition:
    - condition: state
      entity_id: input_boolean.vacuum_on_leave
      state: 'on'
    - condition: state
      entity_id: person.daniel
      state: 'not_home'
    - condition: state
      entity_id: person.laura
      state: 'not_home'
  action:
    - service: vacuum.turn_on
      entity_id: vacuum.xiaomi_vacuum_cleaner
    - service: input_boolean.turn_off
      entity_id: input_boolean.vacuum_on_leave
