# Turn on TV and adjust receiver to match volume
- alias: TV Time
  hide_entity: True
  trigger:
    - platform: state
      entity_id: input_boolean.TV_time
      from: 'off'
      to: 'on'      
  action: 
    - service: media_player.turn_on
      entity_id: media_player.sony_bravia_tv
    - service: media_player.select_source
      entity_id: media_player.sony_bravia_tv
      data:
        source: 'NPO 1 HD'        
    - service: media_player.select_source
      entity_id: media_player.denon_avrx1300w
      data: 
        source: 'TV Audio'
    - delay: 00:00:05
    - service: media_player.volume_set
      entity_id: media_player.denon_avrx1300w
      data: 
        volume_level: "0.50"
    - service: input_boolean.turn_off
      entity_id: input_boolean.TV_time        

# Turn on TV and switch to correct HDMI input
- alias: Game Time
  hide_entity: True
  trigger:
    - platform: state
      entity_id: input_boolean.game_time
      to: 'on'
      from: 'off'
  action: 
    - service: media_player.turn_on
      entity_id: media_player.sony_bravia_tv
    - service: media_player.select_source
      entity_id: media_player.sony_bravia_tv
      data:
        source: 'HDMI 3/ARC'
    - service: media_player.select_source
      entity_id: media_player.denon_avrx1300w
      data: 
        source: Game
    - delay: 00:00:01
    - service: input_boolean.turn_off
      entity_id: input_boolean.game_time
