# Turn on away mode when everybody leaves
- alias: 'Turn on away mode when everybody leaves'
  trigger:
    - platform: state
      entity_id: device_tracker.daniels_iphone, device_tracker.lauras_iphone
      to: 'not_home'
  condition:
    - condition: state
      entity_id: input_boolean.guest_mode
      state: 'off'
    - condition: state
      entity_id: device_tracker.daniels_iphone
      state: 'not_home'
    - condition: state
      entity_id: device_tracker.lauras_iphone
      state: 'not_home'
  action:
    service: input_boolean.turn_on
    entity_id: input_boolean.away_mode

# Turn off away mode when anybode arrives at home
- alias: 'Turn off away mode when somebody arrives at home'
  trigger:
    - platform: state
      entity_id: device_tracker.daniels_iphone, device_tracker.lauras_iphone
      to: 'home'
  action:
    service: input_boolean.turn_off
    entity_id: input_boolean.away_mode
