# Turn on tv, by short press on switch
- alias: TV time by switch press
  hide_entity: True
  trigger:
    - platform: event
      event_type: click
      event_data:
        entity_id: binary_sensor.switch_158d00014a11c5
        click_type: single
  action: 
    - service: input_boolean.turn_on
      data:
        entity_id: input_boolean.tv_time

# Turn on bedtime, by long press on switch
- alias: Bed time by switch press
  hide_entity: True
  trigger:
    - platform: event
      event_type: click
      event_data:
        entity_id: binary_sensor.switch_158d00014a11c5
        click_type: long_click_press
  action: 
    - service: input_boolean.turn_on
      data:
        entity_id: input_boolean.bed_time

# Turn on wakeup ligh, by long press on switch
- alias: Turn on wakeup light
  hide_entity: True
  trigger:
    - platform: event
      event_type: click
      event_data:
        entity_id: binary_sensor.wall_switch_right_158d000163babb
        click_type: single
  action: 
    - service: light.toggle
      data:
        entity_id: light.wakeup