input_boolean:
  bed_time:
    name: Bedtime Mode
    initial: 'off'
    icon: mdi:sleep

automation:
  # Turn on bedtime, turn off livingroom devices
  - alias: Bed time
    initial_state: 'true'
    trigger:
      - platform: state
        entity_id: input_boolean.bed_time
        from: 'off'
        to: 'on'
    action:
      - service: script.turn_off_multimedia_devices
      - service: script.turn_off_lights
      - service: input_boolean.turn_off
        entity_id: input_boolean.guest_mode
      - service: input_boolean.turn_off
        entity_id: input_boolean.evening_time

  # Turn off bed time at 6 am
  - alias: Bed time - Turn off
    initial_state: 'true'
    trigger:
      - platform: time
        at: '06:00:00'
    action:
      - service: input_boolean.turn_off
        entity_id: input_boolean.bed_time
