# Example configuration.yaml entry using 'input_number' in an action in an automation
input_number:
  blinds_slider:
    name: Blinds Slider
    min: 0
    max: 180
    step: 1
    unit_of_measurement: step
    icon: mdi:target

# This automation script runs when a value is received via MQTT on retained topic: setTemperature
# It sets the value slider on the GUI. This slides also had its own automation when the value is changed.
automation:
  - alias: Set blind position from mqtt
    trigger:
      platform: mqtt
      topic: 'my/custom/topic'
    action:
      service: input_number.set_value
      data_template:
        entity_id: input_number.blinds_slider
        value: "{{ trigger.payload }}"

# This second automation script runs when the target temperature slider is moved.
# It publishes its value to the same MQTT topic it is also subscribed to.
  - alias: Set blind position from hass
    trigger:
      platform: state
      entity_id: input_number.blinds_slider
    action:
      service: mqtt.publish
      data_template:
        topic: 'my/custom/topic'
        retain: true
        payload: "{{ states('input_number.blinds_slider') | int }}"
