# Ring doorbell
# binary_sensor:
#   - platform: ring
# ring:
#   username: !secret ring_username
#   password: !secret ring_password

stream:

camera:
  # - platform: ring
  - platform: uvc
    nvr: !secret unifi_nvr_ip
    key: !secret unifi_nvr_key
    password: !secret unifi_nvr_camera_password
    ssl: false
  - platform: ffmpeg
    name: !secret wyzecam_name_1
    input: !secret wyzecam_url_1

binary_sensor:
  - platform: ffmpeg_motion
    name: !secret wyzecam_name_1
    input: !secret wyzecam_url_1
