input_boolean:
  away_mode:
    name: Away Mode
    initial: 'off'
    icon: mdi:human-greeting
  guest_mode:
    name: Guest Mode
    initial: 'off'
    icon: mdi:account-check
  vacation_mode:
    name: Vacation Mode
    initial: 'off'
    icon: mdi:airplane-takeoff

automation:
  - alias: 'Turn on away mode when everybody leaves'
    trigger:
      - platform: state
        entity_id: person.daniel, person.laura
        to: 'not_home'
    condition:
      - condition: state
        entity_id: input_boolean.guest_mode
        state: 'off'
      - condition: state
        entity_id: person.daniel
        state: 'not_home'
      - condition: state
        entity_id: person.laura
        state: 'not_home'
    action:
      service: input_boolean.turn_on
      entity_id: input_boolean.away_mode

  # Turn off away mode when anybode arrives at home
  # also turn off guest mode when arriving home
  - alias: 'Turn off away mode when somebody arrives at home'
    trigger:
      - platform: state
        entity_id: person.daniel, person.laura
        to: 'home'
    action:
      - service: input_boolean.turn_off
        entity_id: input_boolean.away_mode
      - service: input_boolean.turn_off
        entity_id: input_boolean.guest_mode
