light:
  - platform: group
    name: Livingroom
    entities:
      - light.bank
      # - light.kast
      - light.tv_kast
      - light.livingroom_downlights
  - platform: group
    name: Kitchen
    entities:
      - light.kitchen_cabinets
      - light.kitchen_island
  - platform: group
    name: Dining
    entities:
      - light.dinner_table
  - platform: group
    name: Hall
    entities:
      - light.front_door
  # Group by floors
  - platform: group
    name: Downstairs
    entities:
      - light.kitchen
      - light.livingroom
      - light.dining
      - light.hall

  # - platform: group
  #   name: Outside
  #   entities:
  #     - light.dinner_table
  
input_select:
  last_scene:
    name: Last scene
    options:
      - 'All Off'
      - 'All On'
      - Nightlight
      - Relax
      - Concentrate
      - Movie
      - 'Dinner Time'
      - 'Breakfast Time'
    initial: 'All Off'
    icon: mdi:floor-lamp

  livingroom_scenes:
    name: Livingroom scenes
    options:
      - relax
      - concentrate
      - movie
      - nightlight
    # initial: 'All Off'
    icon: mdi:floor-lamp


# Sun sensors
sensor:
  - platform: template
    sensors:
      nextsunrise:
        friendly_name: 'Next Sun Rise'
        value_template: "{{ as_timestamp(states.sun.sun.attributes.next_rising) | timestamp_custom('%-H:%M') }}"
        icon_template: mdi:weather-sunset-up

  - platform: template
    sensors:
      nextsunset:
        friendly_name: 'Next Sun Set'
        value_template: "{{ as_timestamp(states.sun.sun.attributes.next_setting) | timestamp_custom('%-H:%M') }}"
        icon_template: mdi:weather-sunset-down

script:
  turn_off_lights:
    alias: 'Turn off all first floor lights with delay'
    sequence:
      - service: light.turn_off
        data:
          entity_id: light.tv_kast
          flash: short
      - service: light.turn_off
        data:
          entity_id: light.bank
          flash: short
      - service: light.turn_off
        data:
          entity_id: light.livingroom
          transition: 30
      - service: light.turn_off
        data:
          entity_id: light.kitchen
          transition: 30
      - service: light.turn_off
        data:
          entity_id: light.dining
          transition: 30

automation:
  - alias: Scroll livingroom scenes on switch press
    initial_state: 'true'
    hide_entity: false
    trigger:
      - platform: event
        event_type: zwave.scene_activated
        event_data:
          scene_id: 26
    action:
      - service: input_select.select_next
        data:
          entity_id: input_select.livingroom_scenes

  - alias: Set selected livingroom scene
    initial_state: 'true'
    hide_entity: false
    trigger:
      - platform: state
        entity_id: input_select.livingroom_scenes
    action:
      - service: scene.turn_on
        data_template:
          entity_id: >
            scene.{{ states("input_select.livingroom_scenes") }}
