# Set booleans and automations for detecting
# in house presence by motion sensors. Inspiration from
# https://www.home-assistant.io/cookbook/turn_on_light_for_10_minutes_when_motion_detected/

input_boolean:
  livingroom_presence:
    name: Livingroom presence
    initial: false
    icon: mdi:walk
  kitchen_presence:
    name: Kitchen presence 
    initial: false
    icon: mdi:walk

automation:
  - alias: Trigger livingroom presence on
    initial_state: 'true'
    hide_entity: false
    trigger:
      - platform: state
        entity_id: binary_sensor.livingroom_motion
        to: 'on'
    action:
      - service: input_boolean.turn_on
        entity_id: input_boolean.livingroom_presence

  - alias: Set livingroom presence off
    initial_state: 'true'
    hide_entity: 'false'
    trigger:
      - platform: state
        entity_id: binary_sensor.livingroom_motion
        to: 'off'
        for:
          minutes: 5
    action:
      - service: input_boolean.turn_off
        entity_id: input_boolean.livingroom_presence

  - alias: Set kitchen presence on
    initial_state: 'true'
    hide_entity: 'false'
    trigger:
      - platform: state
        entity_id: binary_sensor.motion_kitchen_front, binary_sensor.motion_kitchen_back
        to: 'on'
    action:
      - service: input_boolean.turn_on
        entity_id: input_boolean.kitchen_presence

  - alias: Set kitchen presence off
    initial_state: 'true'
    hide_entity: 'false'
    trigger:
      - platform: state
        entity_id: binary_sensor.motion_kitchen_front, binary_sensor.motion_kitchen_back
        to: 'off'
        for:
          minutes: 5
    action:
      - service: input_boolean.turn_off
        entity_id: input_boolean.kitchen_presence
