# Set booleans and automations for detecting
# in house presence by motion sensors. Inspiration from
# https://www.home-assistant.io/cookbook/turn_on_light_for_10_minutes_when_motion_detected/

input_boolean:
  livingroom_presence:
    name: Livingroom presence
    initial: false
    icon: mdi:walk
  kitchen_presence:
    name: Kitchen presence 
    initial: false
    icon: mdi:walk
  # Modes that make home assistant behave differently

automation:
    # Livingroom presence
  - alias: Trigger livingroom presence on motion
    initial_state: 'true'
    trigger:
      - platform: state
        entity_id: binary_sensor.livingroom_motion
        to: 'on'
    action:
      - service: input_boolean.turn_on
        entity_id: input_boolean.livingroom_presence
  - alias: Set livingroom presence off
    initial_state: 'true'
    trigger:
      - platform: state
        entity_id: binary_sensor.livingroom_motion
        to: 'off'
        for:
          minutes: 5
    action:
      - service: input_boolean.turn_off
        entity_id: input_boolean.livingroom_presence

    # Kitchen presence
  - alias: Turn on kitchen presence on motion
    initial_state: 'true'
    trigger:
      - platform: state
        entity_id: binary_sensor.kitchen_back_motion_zone, binary_sensor.kitchen_front_motion_zone
        to: 'on'
    action:
      - service: input_boolean.turn_on
        entity_id: input_boolean.kitchen_presence
      - service: timer.cancel
        entity_id: timer.kitchen_presence
      # - service: timer.start
      #   data:
      #     entity_id: timer.kitchen_presence

  - alias: Start timer to turn off kitchen presence
    initial_state: 'true'
    trigger:
      - platform: state
        entity_id: binary_sensor.kitchen_back_motion_zone, binary_sensor.kitchen_front_motion_zone
        to: 'off'
    condition:
      condition: and
      conditions:
        - condition: state
          entity_id: 'binary_sensor.kitchen_back_motion_zone'
          state: 'off'
        - condition: state
          entity_id: 'binary_sensor.kitchen_front_motion_zone'
          state: 'off'
    action:
      - service: timer.start
        data:
          entity_id: timer.kitchen_presence

  - alias: Turn off kitchen presence when timer is finished
    initial_state: 'true'
    trigger:
    - platform: event
      event_type: timer.finished
      event_data:
        entity_id: timer.kitchen_presence
    action:
      - service: input_boolean.turn_off
        entity_id: input_boolean.kitchen_presence

timer:
  kitchen_presence:
    duration: '00:05:00'
  livingroom_presence:
    duration: '00:20:00'