input_boolean:
  tv_time:
    name: Watch TV
    initial: 'off'
    icon: mdi:television
  game_time:
    name: Play a game
    initial: 'off'
    icon: mdi:xbox

automation:
  # Turn on TV and adjust receiver to match volume
  - alias: TV Time
    initial_state: 'on'
    trigger:
      - platform: state
        entity_id: input_boolean.tv_time
        from: 'off'
        to: 'on'
    action:
      - service: media_player.turn_on
        entity_id: media_player.sony_bravia_tv
      - service: media_player.select_source
        entity_id: media_player.sony_bravia_tv
        data:
          source: 'NPO 1 HD'
      - service: media_player.select_source
        entity_id: media_player.denon_avrx1300w
        data:
          source: 'TV Audio'
      - delay: 00:00:05
      - service: media_player.volume_set
        entity_id: media_player.denon_avrx1300w
        data:
          volume_level: "0.50"
      - service: input_boolean.turn_off
        entity_id: input_boolean.tv_time

  # Turn on TV and switch to correct HDMI input
  - alias: Game Time
    trigger:
      - platform: state
        entity_id: input_boolean.game_time
        to: 'on'
        from: 'off'
    action:
      - service: media_player.turn_on
        entity_id: media_player.sony_bravia_tv
      - service: media_player.select_source
        entity_id: media_player.sony_bravia_tv
        data:
          source: 'HDMI 3/ARC'
      - service: media_player.select_source
        entity_id: media_player.denon_avrx1300w
        data:
          source: Game
      - delay: 00:00:01
      - service: input_boolean.turn_off
        entity_id: input_boolean.game_time
