
input_select:
  fanstate:
    name: Ventilation Fan
    options:
      - Low
      - Medium
      - High
    initial: Medium
    icon: mdi:fan

automation:
  - id: set_fan_state
    alias: Fan Speed high
    trigger:
    - platform: state
      entity_id: input_select.fanstate
    action:
    - service: mqtt.publish
      data_template:
        topic: itho/cmd
        payload: 'ithosend,{{ states.input_select.fanstate.state }}'