input_boolean:
  wakeup_time:
    name: Wake up time
    initial: 'off'
    icon: mdi:bell-sleep

automation:
  # Trigger wakeup time on movement in the morning
  - alias: Trigger wakeup time on motion in the morning
    initial_state: 'true'
    trigger:
      - platform: state
        # TODO: add motion in the kitchen as well
        entity_id: 
          - binary_sensor.livingroom_motion_zone
          - binary_sensor.kitchen_back_motion_zone
          - binary_sensor.kitchen_front_motion_zone
        to: 'on'
    condition:
      condition: and
      conditions:
        - condition: state
          entity_id: 'input_boolean.wakeup_time'
          state: 'off'
        - condition: time
          after: '06:00:00'
          before: '10:00:00'
    action:
      - service: input_boolean.turn_on
        entity_id: input_boolean.wakeup_time

  # Turn off wakeup time after 10 am
  - alias: Turn off Wakeup time
    trigger:
      - platform: time
        at: '10:01:00'
    action:
      - service: input_boolean.turn_off
        entity_id: input_boolean.wakeup_time

  # Turn on the light based on wakeup time trigger low lux and before sunrise.
  - alias: Turn on livingroom lights before sunrise on wakeup time
    initial_state: 'true'
    trigger:
      - platform: state
        entity_id: input_boolean.wakeup_time
        from: 'off'
        to: 'on'
    condition:
      condition: and
      conditions:
        - condition: numeric_state
          entity_id: sensor.livingroom_light
          below: 80
        - condition: state
          entity_id: 'light.livingroom'
          state: 'off'
        - condition: sun
          before: sunrise
        - condition: state
          entity_id: input_boolean.away_mode
          state: 'off'
    action:
      - service: scene.turn_on
        entity_id: scene.breakfast_time
